### ISSUE TITLE
v1 bug: Panic on context.IsSet(flag) and context.NumFlags() with bash completions

### ISSUE THREAD

**Issue by knopt** [urfave/cli#1095]
## my urfave/cli version is

_**( v1.22.3 )**_

## Checklist

* [x] Are you running the latest v1 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v1 manual is [here](https://github.com/urfave/cli/blob/master/docs/v1/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [ ] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

CLI panics sometimes on method `func (c *Context) IsSet(name string)` because of `c.flagSet` being `nil`. The same with `func (c *Context) NumFlags()` for the same reason.

## To reproduce

```go
func suggestFlags(c *cli.Context) {
	for _, flag := range c.Command.Flags {
		if c.IsSet(flag.GetName()) {
			continue
		}

		fmt.Printf("--%s\n", flag.GetName())
	}
}

func main() {
	app := cli.NewApp()
	app.Name = "example"
	app.EnableBashCompletion = true
	app.Commands = []cli.Command{{
		Name:   "cmd",
		Action: func(c *cli.Context) error { return nil },
		Flags:  []cli.Flag{cli.StringFlag{Name: "a"}, cli.StringFlag{Name: "b"}},
		BashComplete: func(c *cli.Context) {
			suggestFlags(c)
		},
	}}
	app.Action = func(c *cli.Context) error {
		fmt.Println("Hello friend!")
		return nil
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}

```
1. Build the code above.
2. Enable completions
3. `example cmd --a [TAB]` 

## Observed behavior

```console
runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4d9c42]

goroutine 1 [running]:
flag.(*FlagSet).Visit(0x0, 0xc0000dd6b0)
	/usr/local/go/src/flag/flag.go:398 +0x22
github.com/urfave/cli.(*Context).IsSet(0xc0000a22c0, 0x5ca304, 0x1, 0x590280)
	$GOPATH/go/pkg/mod/github.com/urfave/cli@v1.22.2/context.go:59 +0x8f
main.suggestFlags(0xc0000a22c0)
```

## Expected behavior

I expected `--b` to be suggested, resulting in `example cmd --a --b` 

## Additional context
```console
$ echo $SHELL
/usr/bin/zsh
$ zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

## Run `go version` and paste its output here

```
go version go1.13.7 linux/amd64
```

**Comment by lynncyrin** [comment]
Makes sense! @knopt or @ anyone else, PRs are welcome 🙏

**Comment by xordspar0** [comment]
I'm not able to reproduce this on master. Did it get fixed? This is what I see when I do `set -x` and press tab:

```
./example cmd --a 
+ [[ ./example != \s\o\u\r\c\e ]]
+ local cur opts base
+ COMPREPLY=()
+ cur=
+ [[ '' == \-* ]]
++ ./example cmd --a --generate-bash-completion
+ opts='--a
--b
--help, h'
+ COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
++ compgen -W '--a
--b
--help, h' --
+ return 0
```

**Comment by dearchap** [comment]
Not reproducible in v1.22.10
