### ISSUE TITLE
v2 bug: panics if EnvVar of a StringSliceFlag is wrong

### ISSUE THREAD

**Issue by 6543** [urfave/cli#1339]
## my urfave/cli version is

_**github.com/urfave/cli/v2 v2.3.0**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [ ] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [ ] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.
- [x] My project is using vendoring.
- [ ] My project is automatically downloading the latest version.
- [ ] I am unsure of what my dependency management setup is.

## Describe the bug

if for example we set `WOODPECKER_ENVIRONMENT=k:v,foo=bar`
and use it at:
```go
	&cli.StringSliceFlag{
		EnvVars: []string{"WOODPECKER_ENVIRONMENT"},
		Name:    "environment",
	},
```

we get a panic stack trace:
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/woodpecker-ci/woodpecker/server/plugins/environments.Filesystem(0xc0004cd780, 0x4, 0x4, 0xc0004cd780, 0x4)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/plugins/environments/filesystem.go:19 +0x2a8
main.setupEnvironService(0xc000240c80, 0x142d6c8, 0xc000194430, 0x7f2b240a3140, 0xc000194430)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/setup.go:176 +0x67
main.setupEvilGlobals(0xc000240c80, 0x142d6c8, 0xc000194430, 0x1425300, 0xc0006aa180)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/server.go:273 +0x45c
main.run(0xc000240c80, 0x0, 0x0)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/server.go:122 +0x413
github.com/urfave/cli/v2.(*App).RunContext(0xc0001a0680, 0x1418a68, 0xc000044040, 0xc000034220, 0x1, 0x1, 0x0, 0x0)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/urfave/cli/v2/app.go:322 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/urfave/cli/v2/app.go:224
main.main()
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/cmd/server/main.go:35 +0x134
```

## To reproduce

Use the woodpecker builds or write your own testcase

## Observed behavior

panic

## Expected behavior

no panic

## Additional context

original issue: https://github.com/woodpecker-ci/woodpecker/issues/761

**Comment by 6543** [comment]
sorry should have looked closer to the stactrasce :D
