### ISSUE TITLE
golang: flag redefined: jwt_issuerq: ( your question title goes here )

### ISSUE THREAD

**Issue by tpnfocal** [urfave/cli#1345]
I'm using flag and cli.Flag in my project for upgrade go version for this project but it have issue.

When i used &cli.StringFlag for set command line config, it show error when I run this project by realize

```
[20:06:34][PROJECT] : myproject flag redefined: jwt_issuer
[20:06:34][PROJECT] : panic: myproject flag redefined: jwt_issuer
[20:06:34][PROJECT] : goroutine 1 [running]:
[20:06:34][PROJECT] : flag.(*FlagSet).Var(0x140004aefc0, {0x103e91808, 0x140004c9d30}, {0x14000528a40, 0xa}, {0x1039c3c5e, 0xa})
[20:06:34][PROJECT] :   /usr/local/go/src/flag/flag.go:879 +0x2d8
[20:06:34][PROJECT] : flag.(*FlagSet).StringVar(...)
[20:06:34][PROJECT] :   /usr/local/go/src/flag/flag.go:762
[20:06:34][PROJECT] : flag.(*FlagSet).String(0x140004aefc0, {0x14000528a40, 0xa}, {0x1039c7783, 0xd}, {0x1039c3c5e, 0xa})
[20:06:34][PROJECT] :   /usr/local/go/src/flag/flag.go:775 +0xa0
[20:06:34][PROJECT] : github.com/urfave/cli/v2.(*StringFlag).Apply(0x14000538640, 0x140004aefc0)
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/flag_string.go:75 +0x1b0
[20:06:34][PROJECT] : github.com/urfave/cli/v2.flagSet({0x1039bed54, 0x7}, {0x140004baf00, 0x31, 0x50})
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/flag.go:134 +0x158
[20:06:34][PROJECT] : github.com/urfave/cli/v2.(*App).newFlagSet(...)
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:214
[20:06:34][PROJECT] : github.com/urfave/cli/v2.(*App).RunContext(0x1400022a820, {0x103e9cfd8, 0x140000400b8}, {0x1400003c1e0, 0x1, 0x1})
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:241 +0x114
[20:06:34][PROJECT] : github.com/urfave/cli/v2.(*App).Run(...)
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
[20:06:34][PROJECT] : github.com/urfave/cli/v2.(*App).RunAndExitOnError(0x1400022a820)
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:334 +0x64
[20:06:34][PROJECT] : go-micro.dev/v4/cmd.(*cmd).Init(0x14000240360, {0x14000489770, 0xa, 0xa})
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/go-micro.dev/v4@v4.6.0/cmd/cmd.go:642 +0x114
[20:06:34][PROJECT] : go-micro.dev/v4.(*service).Init.func1()
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/go-micro.dev/v4@v4.6.0/service.go:93 +0x574
[20:06:34][PROJECT] : sync.(*Once).doSlow(0x14000260d98, 0x140001579e8)
[20:06:34][PROJECT] :   /usr/local/go/src/sync/once.go:68 +0x10c
[20:06:34][PROJECT] : sync.(*Once).Do(...)
[20:06:34][PROJECT] :   /usr/local/go/src/sync/once.go:59
[20:06:34][PROJECT] : go-micro.dev/v4.(*service).Init(0x14000260c60, {0x14000011730, 0x1, 0x1})
[20:06:34][PROJECT] :   /Users/myuser/go/pkg/mod/go-micro.dev/v4@v4.6.0/service.go:68 +0x94
[20:06:34][PROJECT] : main.InitialService()
[20:06:34][PROJECT] :   /Users/myuser/Documents/Working/hospital-go/services/myproject/server/main.go:88 +0x4e4
[20:06:34][PROJECT] : main.main()
[20:06:34][PROJECT] :   /Users/myuser/Documents/Working/hospital-go/services/myproject/server/main.go:25 +0x48
```

**Comment by rliebz** [comment]
> myproject flag redefined: jwt_issuer

This looks a lot like an app named `myproject` with a flag named `jwt_issuer` defined more than once. Each flag defined must have a unique name.

See here for a reproduction: https://play.golang.com/p/8xkHoHY4tIx

Remove one of the duplicate flags, and the error goes away.

**Comment by tpnfocal** [comment]
Oh god! Thanks for my answer my issuer.
