### ISSUE TITLE
app.Run panics on amd64 architecture with "exec format error"

### ISSUE THREAD

**Issue by therealplato** [urfave/cli#667]
I googled the error messages and found several other people reporting the same issue. Couldn't find an existing issue for this behavior. My binary (using `gopkg.in/urfave/cli.v1`) runs fine locally on `darwin` architecture but when deploying to `GOOS=linux GOARCH=amd64` (kubernetes 1.5.2) this panic occurs:
```
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7ea960, 0xc82016a8c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200b52f8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea960, 0xc82016a8c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200b4c08, 0xc8200220a0, 0xc8200b4d18)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820060870, 0x7f2435101488, 0xc82016a8c0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820080780, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f160, 0x900ae8, 0x13, 0x846e88, 0x4, 0xc8200b5278, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f160, 0x900ae8, 0x13, 0xc8200b5278, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f160, 0x900ae8, 0xc820080780, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849d38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dfde0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Comment by jszwedko** [comment]
@therealplato this seems like you are attempting to run an incompatible binary (rather than an issue with `urfave/cli`). What version of Go are you running? Are you able to compile and run a "hello world" program not using this library?

**Comment by therealplato** [comment]
Yep. PEBCAK :)

**Comment by jszwedko** [comment]
No worries :)
